
package gr.opap.draws.ws.query;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DrawQueriesServiceImplService", targetNamespace = "http://query.ws.draws.opap.gr/", wsdlLocation = "http://applications.opap.gr/DrawsQueryServices/services/DrawQueriesServiceImplPort?wsdl")
public class DrawQueriesServiceImplService
    extends Service
{

    private final static URL DRAWQUERIESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRAWQUERIESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DRAWQUERIESSERVICEIMPLSERVICE_QNAME = new QName("http://query.ws.draws.opap.gr/", "DrawQueriesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://applications.opap.gr/DrawsQueryServices/services/DrawQueriesServiceImplPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRAWQUERIESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DRAWQUERIESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DrawQueriesServiceImplService() {
        super(__getWsdlLocation(), DRAWQUERIESSERVICEIMPLSERVICE_QNAME);
    }

    public DrawQueriesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRAWQUERIESSERVICEIMPLSERVICE_QNAME, features);
    }

    public DrawQueriesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DRAWQUERIESSERVICEIMPLSERVICE_QNAME);
    }

    public DrawQueriesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRAWQUERIESSERVICEIMPLSERVICE_QNAME, features);
    }

    public DrawQueriesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DrawQueriesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DrawQueriesServiceSEI
     */
    @WebEndpoint(name = "DrawQueriesServiceImplPort")
    public DrawQueriesServiceSEI getDrawQueriesServiceImplPort() {
        return super.getPort(new QName("http://query.ws.draws.opap.gr/", "DrawQueriesServiceImplPort"), DrawQueriesServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DrawQueriesServiceSEI
     */
    @WebEndpoint(name = "DrawQueriesServiceImplPort")
    public DrawQueriesServiceSEI getDrawQueriesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://query.ws.draws.opap.gr/", "DrawQueriesServiceImplPort"), DrawQueriesServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRAWQUERIESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DRAWQUERIESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DRAWQUERIESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
