
package gr.opap.draws.ws.query;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DrawQueriesServiceSEI", targetNamespace = "http://query.ws.draws.opap.gr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DrawQueriesServiceSEI {


    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchLottoDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchLottoDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLottoDrawByNumber")
    @ResponseWrapper(localName = "fetchLottoDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLottoDrawByNumberResponse")
    public GameDraw fetchLottoDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.PropoDraw>
     */
    @WebMethod(action = "urn:FetchPropoDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPropoDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoDrawsByDate")
    @ResponseWrapper(localName = "fetchPropoDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoDrawsByDateResponse")
    public List<PropoDraw> fetchPropoDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchProtoDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchProtoDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchProtoDrawByNumber")
    @ResponseWrapper(localName = "fetchProtoDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchProtoDrawByNumberResponse")
    public GameDraw fetchProtoDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchPropoGoalDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPropoGoalDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoGoalDrawsByDate")
    @ResponseWrapper(localName = "fetchPropoGoalDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoGoalDrawsByDateResponse")
    public List<GameDraw> fetchPropoGoalDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchBowlingDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchBowlingDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchBowlingDrawsByDate")
    @ResponseWrapper(localName = "fetchBowlingDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchBowlingDrawsByDateResponse")
    public List<GameDraw> fetchBowlingDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @param dayNum
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.PropoDraw
     */
    @WebMethod(action = "urn:FetchPropoDrawByNumberAndDay")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPropoDrawByNumberAndDay", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoDrawByNumberAndDay")
    @ResponseWrapper(localName = "fetchPropoDrawByNumberAndDayResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoDrawByNumberAndDayResponse")
    public PropoDraw fetchPropoDrawByNumberAndDay(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo,
        @WebParam(name = "dayNum", targetNamespace = "")
        long dayNum);

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchBowlingDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchBowlingDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchBowlingDrawByNumber")
    @ResponseWrapper(localName = "fetchBowlingDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchBowlingDrawByNumberResponse")
    public GameDraw fetchBowlingDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchJokerDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchJokerDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchJokerDrawByNumber")
    @ResponseWrapper(localName = "fetchJokerDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchJokerDrawByNumberResponse")
    public GameDraw fetchJokerDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchProtoLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchProtoLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchProtoLatestDraw")
    @ResponseWrapper(localName = "fetchProtoLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchProtoLatestDrawResponse")
    public GameDraw fetchProtoLatestDraw();

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchPowerSpinDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPowerSpinDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPowerSpinDrawByNumber")
    @ResponseWrapper(localName = "fetchPowerSpinDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPowerSpinDrawByNumberResponse")
    public GameDraw fetchPowerSpinDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchKinoDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchKinoDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchKinoDrawsByDate")
    @ResponseWrapper(localName = "fetchKinoDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchKinoDrawsByDateResponse")
    public List<GameDraw> fetchKinoDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.PropoDraw
     */
    @WebMethod(action = "urn:FetchLatestPropoSundayDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchLatestPropoSundayDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLatestPropoSundayDraw")
    @ResponseWrapper(localName = "fetchLatestPropoSundayDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLatestPropoSundayDrawResponse")
    public PropoDraw fetchLatestPropoSundayDraw();

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchLottoLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchLottoLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLottoLatestDraw")
    @ResponseWrapper(localName = "fetchLottoLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLottoLatestDrawResponse")
    public GameDraw fetchLottoLatestDraw();

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchJokerDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchJokerDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchJokerDrawsByDate")
    @ResponseWrapper(localName = "fetchJokerDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchJokerDrawsByDateResponse")
    public List<GameDraw> fetchJokerDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchKinoLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchKinoLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchKinoLatestDraw")
    @ResponseWrapper(localName = "fetchKinoLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchKinoLatestDrawResponse")
    public GameDraw fetchKinoLatestDraw();

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchSuper3DrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchSuper3DrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchSuper3DrawsByDate")
    @ResponseWrapper(localName = "fetchSuper3DrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchSuper3DrawsByDateResponse")
    public List<GameDraw> fetchSuper3DrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchPenaltiesDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPenaltiesDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPenaltiesDrawByNumber")
    @ResponseWrapper(localName = "fetchPenaltiesDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPenaltiesDrawByNumberResponse")
    public GameDraw fetchPenaltiesDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchProtoDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchProtoDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchProtoDrawsByDate")
    @ResponseWrapper(localName = "fetchProtoDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchProtoDrawsByDateResponse")
    public List<GameDraw> fetchProtoDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchPenaltiesLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPenaltiesLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPenaltiesLatestDraw")
    @ResponseWrapper(localName = "fetchPenaltiesLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPenaltiesLatestDrawResponse")
    public GameDraw fetchPenaltiesLatestDraw();

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchExtra5DrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchExtra5DrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchExtra5DrawByNumber")
    @ResponseWrapper(localName = "fetchExtra5DrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchExtra5DrawByNumberResponse")
    public GameDraw fetchExtra5DrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchPenaltiesDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPenaltiesDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPenaltiesDrawsByDate")
    @ResponseWrapper(localName = "fetchPenaltiesDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPenaltiesDrawsByDateResponse")
    public List<GameDraw> fetchPenaltiesDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchJokerLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchJokerLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchJokerLatestDraw")
    @ResponseWrapper(localName = "fetchJokerLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchJokerLatestDrawResponse")
    public GameDraw fetchJokerLatestDraw();

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.PropoDraw
     */
    @WebMethod(action = "urn:FetchLatestPropoSaturdayDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchLatestPropoSaturdayDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLatestPropoSaturdayDraw")
    @ResponseWrapper(localName = "fetchLatestPropoSaturdayDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLatestPropoSaturdayDrawResponse")
    public PropoDraw fetchLatestPropoSaturdayDraw();

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchExtra5DrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchExtra5DrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchExtra5DrawsByDate")
    @ResponseWrapper(localName = "fetchExtra5DrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchExtra5DrawsByDateResponse")
    public List<GameDraw> fetchExtra5DrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchSuper3DrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchSuper3DrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchSuper3DrawByNumber")
    @ResponseWrapper(localName = "fetchSuper3DrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchSuper3DrawByNumberResponse")
    public GameDraw fetchSuper3DrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchPowerSpinDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPowerSpinDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPowerSpinDrawsByDate")
    @ResponseWrapper(localName = "fetchPowerSpinDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPowerSpinDrawsByDateResponse")
    public List<GameDraw> fetchPowerSpinDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchBowlingLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchBowlingLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchBowlingLatestDraw")
    @ResponseWrapper(localName = "fetchBowlingLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchBowlingLatestDrawResponse")
    public GameDraw fetchBowlingLatestDraw();

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchPropoGoalLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPropoGoalLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoGoalLatestDraw")
    @ResponseWrapper(localName = "fetchPropoGoalLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoGoalLatestDrawResponse")
    public GameDraw fetchPropoGoalLatestDraw();

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchKinoDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchKinoDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchKinoDrawByNumber")
    @ResponseWrapper(localName = "fetchKinoDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchKinoDrawByNumberResponse")
    public GameDraw fetchKinoDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchPowerSpinLatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPowerSpinLatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPowerSpinLatestDraw")
    @ResponseWrapper(localName = "fetchPowerSpinLatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPowerSpinLatestDrawResponse")
    public GameDraw fetchPowerSpinLatestDraw();

    /**
     * 
     * @param drawNo
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchPropoGoalDrawByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPropoGoalDrawByNumber", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoGoalDrawByNumber")
    @ResponseWrapper(localName = "fetchPropoGoalDrawByNumberResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchPropoGoalDrawByNumberResponse")
    public GameDraw fetchPropoGoalDrawByNumber(
        @WebParam(name = "drawNo", targetNamespace = "")
        long drawNo);

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchSuper3LatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchSuper3LatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchSuper3LatestDraw")
    @ResponseWrapper(localName = "fetchSuper3LatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchSuper3LatestDrawResponse")
    public GameDraw fetchSuper3LatestDraw();

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.PropoDraw
     */
    @WebMethod(action = "urn:FetchLatestPropoWednesdayDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchLatestPropoWednesdayDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLatestPropoWednesdayDraw")
    @ResponseWrapper(localName = "fetchLatestPropoWednesdayDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLatestPropoWednesdayDrawResponse")
    public PropoDraw fetchLatestPropoWednesdayDraw();

    /**
     * 
     * @return
     *     returns gr.opap.draws.ws.query.GameDraw
     */
    @WebMethod(action = "urn:FetchExtra5LatestDraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchExtra5LatestDraw", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchExtra5LatestDraw")
    @ResponseWrapper(localName = "fetchExtra5LatestDrawResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchExtra5LatestDrawResponse")
    public GameDraw fetchExtra5LatestDraw();

    /**
     * 
     * @param drawDate
     * @return
     *     returns java.util.List<gr.opap.draws.ws.query.GameDraw>
     */
    @WebMethod(action = "urn:FetchLottoDrawsByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchLottoDrawsByDate", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLottoDrawsByDate")
    @ResponseWrapper(localName = "fetchLottoDrawsByDateResponse", targetNamespace = "http://query.ws.draws.opap.gr/", className = "gr.opap.draws.ws.query.FetchLottoDrawsByDateResponse")
    public List<GameDraw> fetchLottoDrawsByDate(
        @WebParam(name = "drawDate", targetNamespace = "")
        XMLGregorianCalendar drawDate);

}
